### ISSUE TITLE
About the direction in which data is recorded

### ISSUE THREAD

**Issue by yamamov** [juliarose/Steam-Market-History-Cataloger#11]
Thanks for the decimal point support for Japanese Yen. It's a nice program.

Now, a question about recording: once start update record, it seems to keep recording from that point forward into the past, but it doesn't seem to record any future data after "that point". Is it supposed to be used to delete all the data and re-record it?

Suggested improvements
(1) How about saving the data from the recorded data to the latest data once, and then recording back to the past after that?
(2) I think it would be useful to record the "game name" in the csv file to be downloaded, so that it can be searched.

**Comment by juliarose** [comment]
1.
If it is working correctly, it should first collect all listings from most-recent to the beginning. Then upon completion, it will start back at the front and record up until the previous starting point. There was a bug in the most recent version when exporting where results were limited to a certain number (I believe 5000). This was fixed and will be shipped with the next version.

2.
All data is available in the JSON format if you need a specific detail. Though I think a column name for the game name or appid would be useful in the CSV format and will likely put that into the next release.
