### ISSUE TITLE
Update listing stop at a certain point

### ISSUE THREAD

**Issue by dealersway** [juliarose/Steam-Market-History-Cataloger#12]
Hi, i have this issue with my account. it stop update listings at 41275 transactions my account has a total of 50K transactions, it stops loading without giving me an error or something and when i try to reload doesn't work. i also tried to delete all data and start from beginning but isn't work it get stuck on the same point. I also successful load 4 accounts with less transactions. Hope you can help. Thanks

**Comment by juliarose** [comment]
Does it load to the end? Is there anything different about the point it stops loading at?

There is one condition where the counts may be off from what shows on your account on Steam. If a listing was refunded, the listing will not be saved.

**Comment by dealersway** [comment]
it get stuck on the same item, the oldest item that is loading is on 21/08/2018 but i have transactions through 2016

**Comment by juliarose** [comment]
I need more information. What is the item it gets stuck on? What language do you use? Are your transactions in more than one currency?

**Comment by dealersway** [comment]
i ordered by year and it seems to be blocking on a killing floor 2 item "Bolts | Halloween", i keep all in english and is all in euro never used another currency
