### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by Rush-er** [juliarose/Steam-Market-History-Cataloger#2]
Hello,
any plan to add Firefox support ?
Anyway thanks for this it's super handy 😁👍👌

**Comment by juliarose** [comment]
I may consider this at some point if the demand is high enough but it's not a priority right now.

**Comment by Andrey36** [comment]
please fix
eng
Hey. After I downloaded the entire history of sales / purchases(167612 TRANSACTIONS), the "view all" browser does not open, the Google Chrome browser turns off.
rus
Привет. После того как я загрузил всю истории продаж/покупок (167612 TRANSACTIONS) у меня не открывается "view all" браузер гугл хром выключается.=

**Comment by juliarose** [comment]
After over 3 years this extension only has 1000+ users. To me there aren't enough users to warrant also distributing a Firefox version.
