### ISSUE TITLE
Purchase history gives out TypeError: Cannot read properties of undefined (reading 'textContent') 

### ISSUE THREAD

**Issue by AliceApplez** [juliarose/Steam-Market-History-Cataloger#27]
Tried using it both on Edge and Chrome and I keep getting the same error. No idea what's causing it.

The market function itself works and is updating correctly, but purchase history doesn't work

**Comment by juliarose** [comment]
I need more information such as what language and currency your account uses.

**Comment by AliceApplez** [comment]
> I need more information such as what language and currency your account uses.

Randomly remembered this after months so decided why not reply
Currency: Brazillian Reais (BRL)
Language: English

I'm Brazillian but I use the client in English, not PT-BR. currency is in the local one tho
