### ISSUE TITLE
Предложение по улудшению расширения

### ISSUE THREAD

**Issue by aantonsuhininn** [juliarose/Steam-Market-History-Cataloger#31]
Спасибо Вам за Ваш труд. Расширение очень понравилось. Хотел предложить еще добавить в него историю операций обменов. 
Многие из ваших пользователей имеют более одного аккаунта Steam и можно было бы историю этих аккаунтов связать.
Обменявшись предметом с другим своим аккаунтом я теряю возможность следить за историей этого предмета, было бы удобно если бы расширение смогло это исправить.

**Comment by aantonsuhininn** [comment]
Можно сделать специальный сайт куда бы скидывалась вся история со всех аккаунтов. 
Напротив проданого предмета делаем кнопку. Если человек её нажимает, то программа считает прибыль, ищя цену покупки предмета в истории аккаунта и обменов. Если программа определяет что предмет был получен путем обмена, то переходит к истории того вашего аккаунта откуда он был получен.
На этом сайте можно собирать не только историю, можно собирать полную статистику по аккаунту, полный инвентарь с предметами на продаже, вообщем всю информацию о аккаунте. Я считаю это было бы очень удобно.

**Comment by juliarose** [comment]
> Thank you for your work. I really liked the extension. I wanted to suggest adding the history of exchange operations to it.
>
> Many of your users have more than one Steam account and it would be possible to link the history of these accounts.
>
> By exchanging an item with my other account, I lose the ability to follow the history of this item, it would be convenient if the extension could fix this. You can make a special site where the whole history from all accounts would be thrown off.
Opposite the sold item we make a button. If a person presses it, then the program calculates the profit, looking for the purchase price of the item in the history of the account and exchanges. If the program determines that the item was obtained through an exchange, then it goes to the history of your account where it was obtained from.
>
> On this site, you can collect not only history, you can collect complete account statistics, a complete inventory with items for sale, in general, all information about the account. I think it would be very convenient.

Anything related to accounting for profit is outside the scope of this extension. Exporting the data to JSON and creating a program to do the comparisons is an option.
