### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sw1ezy** [juliarose/Steam-Market-History-Cataloger#36]
Hi
Is it possible to add one more column to the exported CSV file, with a direct link to the Steam Market? It would be very helpful. :)

**Comment by juliarose** [comment]
This would be somewhat redundant, you can form the URL using the appid + name.

I'm not sure if this would allow clicking on the link but here's a formula for Microsoft Excel or LibreOffice Calc, or probably most spreadsheet programs which constructs the URL:
`
="https://steamcommunity.com/market/listings/" & D2 & "/" & ENCODEURL(E2)
`

This could easily be added programmatically with a script using any CSV parser.

Here's an example using the papaparse library in node.js:
```js
import Papa from 'papaparse';
import fs from 'fs';

const doc = fs.readFileSync('./records.csv', 'utf8');
const { data } = Papa.parse(doc, {
    header: true
});
// Add a new column to the data
const records = data
    .map((row) => {
        const name = encodeURIComponent(row['Name']);
        const appid = row['App ID'];
        
        row['Url'] = `https://steamcommunity.com/market/listings/${appid}/${name}`;
        return row;
    });
// Convert the data back to CSV
const csv = Papa.unparse(records);

// Write the CSV to a file
fs.writeFileSync('./records-with-urls.csv', csv);
```
