### ISSUE TITLE
Crashes on large number of listings

### ISSUE THREAD

**Issue by juliarose** [juliarose/Steam-Market-History-Cataloger#6]
please fix
eng
Hey. After I downloaded the entire history of sales / purchases(167612 TRANSACTIONS), the "view all" browser does not open, the Google Chrome browser turns off.
rus
Привет. После того как я загрузил всю истории продаж/покупок (167612 TRANSACTIONS) у меня не открывается "view all" браузер гугл хром выключается.=

_Originally posted by @Andrey36 in https://github.com/juliarose/Steam-Market-History-Cataloger/issues/2#issuecomment-671694420_

**Comment by juliarose** [comment]
This may be a memory issue. In order to view all your listings, the extension loads all your listings (all data is included) into memory. This can be a somewhat expensive task.

What hardware are you using?

**Comment by Andrey36** [comment]
Intel Core i7 7700HQ
RAM 16

**Comment by juliarose** [comment]
This should be fixed in v1.1.0. Listings results are now limited when displayed and are queryable against the database as imposed to in-memory. This should reduce memory usage as well as reduce processing demands. This should resolve the issue, however I'll leave this open in case anyone still experiences issues.

**Comment by juliarose** [comment]
Closing this. I believe the issue is resolved other than on totals pages.
